### ISSUE TITLE
OSX Build Does Not Copy/Paste

### ISSUE THREAD

**Issue by sonictail** [StirfireStudios/Jacquard#13]
Copy and Paste does not work in Jacquard via either Command+C and Command V or right click menu.

No work-around found yet.

Running 0.4.0 on OSX 10.13.4.

**Comment by demanrisu** [comment]
Issue also appears in 0.5.0 on OSX 10.11.

**Comment by lordmortis** [comment]
Check release [0.6.0](https://github.com/StirfireStudios/Jacquard/releases/edit/0.6.0)
