### ISSUE TITLE
Issues parsing sample Yarn file

### ISSUE THREAD

**Issue by demanrisu** [StirfireStudios/Jacquard#14]
Jacquard just kinda breaks when presented with a Yarn file that parses normally in other tools.

[YarnSampleTest.yarn.txt](https://github.com/StirfireStudios/Jacquard/files/2111077/YarnSampleTest.yarn.txt)

**Comment by lordmortis** [comment]
This should be working now - can you check it again?

**Comment by demanrisu** [comment]
Appears to work fine aside from the compiler bug we've talked about.
