### ISSUE TITLE
Fail to compile when commands have number parameters

### ISSUE THREAD

**Issue by pjarnfelt** [StirfireStudios/Jacquard#15]
Clicking on the link buttons (shortcuts) opens an empty node page instead of the correct node. 
![link error](https://user-images.githubusercontent.com/891674/41598148-a5d32688-73cf-11e8-875d-148ace046d8b.gif)

**Comment by pjarnfelt** [comment]
In my case it was because it failed to compile. 
This is the "incorrect" formatting that made it all fail: <<runNextLinesTogether 2>>
without the 2 variable there it does not fail.

**Comment by lordmortis** [comment]
Can you try this again with version 0.5.0 ?

**Comment by pjarnfelt** [comment]
Confirmed also on 0.5.0
![jacquard_b15](https://user-images.githubusercontent.com/891674/41716721-aca5b44c-7557-11e8-9e6e-ef1ae9441a9e.gif)

**Comment by lordmortis** [comment]
Can I get the entire yarn file you’re importing?

**Comment by pjarnfelt** [comment]
It's easy enough to validate. Just add <<wait 2>> to any node in any project, then it will fail. I started a new project and did this, and it failed again. 
[failing_minimal_jac.zip](https://github.com/StirfireStudios/Jacquard/files/2123497/failing_minimal_jac.zip)

**Comment by lordmortis** [comment]
Found it, it's an issue in the parser, will be fixed there and rolled into editor version `0.6.0` (with character support.)

**Comment by pjarnfelt** [comment]
Still a problem in my 0.6.0 on windows

**Comment by lordmortis** [comment]
Yep, this isn't fixed.

**Comment by lordmortis** [comment]
Okay, this is super weird. The lock files etc. on my windows machine are up to date, but it's not using the latest parser...

**Comment by pjarnfelt** [comment]
That did it for me. Thanks.
