### ISSUE TITLE
Preview formatting of anything that's not content

### ISSUE THREAD

**Issue by demanrisu** [StirfireStudios/Jacquard#17]
It'd be cool to have the Preview function format all debug/logic output lines differently. Currently, it only highlights node changes - debug output such as `Loaded 2 (number) from variable2` is formatted the same as the content output, which is confusing.
![jacquard4](https://user-images.githubusercontent.com/389964/41670348-3320af8c-74f3-11e8-9e29-8b487c3d1070.JPG)

**Comment by lordmortis** [comment]
easiest thing to do now is border colors/patterns. could also use some [material-ui icons](https://material.io/tools/icons/?style=baseline) maybe? 

We've got the following operations:
  * Command - (done)
  * function call/return 
  * Select choice
  * Enter node
  * load variable
  * save variable
  * halt execution

What do we want to do with each one?

**Comment by demanrisu** [comment]
icon suggestions:
Command - code
Function - settings_ethernet
Select choice - device_hub? / call_split
Enter node - timeline? / subdirectory_right
Load var - mode_comment?
Save var - add_comment
Halt - done

**Comment by lordmortis** [comment]
Check release [0.6.0](https://github.com/StirfireStudios/Jacquard/releases/edit/0.6.0)
