### ISSUE TITLE
visited() does not output a debug log

### ISSUE THREAD

**Issue by demanrisu** [StirfireStudios/Jacquard#18]

**Comment by lordmortis** [comment]
That's strange, isn't it working in the example code? (Also, we probably should output a debug log of all called functions like we do for variable accesses and commands)

**Comment by demanrisu** [comment]
Confirmed that visited() works, just no function output yet

**Comment by lordmortis** [comment]
Check release [0.6.0](https://github.com/StirfireStudios/Jacquard/releases/edit/0.6.0)
