### ISSUE TITLE
New Project, close project bug

### ISSUE THREAD

**Issue by Bas24live** [StirfireStudios/Jacquard#3]
Upon starting the editor and clicking the create a new project button, then clicking the close project button the following error occurs:
![new preoject_close project bug](https://user-images.githubusercontent.com/6557547/40222576-8b96936c-5ab2-11e8-907d-849851c1d1fa.PNG)

**Comment by lordmortis** [comment]
Fixed as of e075aec62592849f6e4a63ac08f1299e1315be72
