### ISSUE TITLE
Character page not working 0.6.0

### ISSUE THREAD

**Issue by pjarnfelt** [StirfireStudios/Jacquard#32]
The setting is enabled, but the page is still disabled:

![characters](https://user-images.githubusercontent.com/891674/41897988-175bf95c-7929-11e8-9217-236de2c2ebff.PNG)

**Comment by lordmortis** [comment]
The parser needs to have support for characters, functions and variables (https://github.com/StirfireStudios/Jacquard-YarnParser/issues/11) - once that's done we can re-enable those pages and actually do something with them.

For now character support is a compiler directive (And characters do work there!)
