### ISSUE TITLE
Importing a yarn file doesn't validate all nodes

### ISSUE THREAD

**Issue by distantcam** [StirfireStudios/Jacquard#6]
![image](https://user-images.githubusercontent.com/1298847/40656501-263e3ace-6377-11e8-8149-d85f6a5eb052.png)

The second node doesn't show a warning for missing tags. This is the yarn.

```
title: Node1
tags: 
colorID: 0
position: 524,111
---
===

title: Node2
tags: 
colorID: 0
position: 524,111
---
===
```

**Comment by demanrisu** [comment]
![image](https://user-images.githubusercontent.com/389964/41723822-35853a1e-75ab-11e8-88ec-739b9d2e2a79.png)

Appears to be fixed, closing.
